name: Publish SignalRGB-Deck StreamDeckPlugin
 
on:
  push:
    tags:
      - 'v*.*.*'

permissions: write-all
jobs:
  build:
    name: MSBuild, Publish and Upload
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.3.1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
           
    - name: Restore NuGet Packages
      run: nuget restore Bill-Z-Bawb-StreamDeck-Plugins.sln
 
    - name: Build and Publish Plugin Deployer Tool
      run: msbuild StreamDeckDeployer\StreamDeckDeployer.csproj /p:Configuration=Publish
    
    - name: Build and Publish Plugin
      run: msbuild SignalRgbDeckPlugin\SignalRgbDeckPlugin.csproj /p:Configuration=Publish
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: published_plugin
        path: SignalRgbDeckPlugin\publish\com.billzbawb.signalrgb.streamDeckPlugin
    
  release:
   name: Make GH Release
   needs: build
   runs-on: ubuntu-latest
   permissions: write-all
   steps:
    - uses: actions/download-artifact@v3
       
    - name: Display structure of downloaded files
      run: ls -R
      
    - uses: 'marvinpinto/action-automatic-releases@latest'
      with:
        repo_token: '${{ secrets.GITHUB_TOKEN }}'
        prerelease: false
        files: |
          published_plugin/com.billzbawb.signalrgb.streamDeckPlugin
          
  bump:
    runs-on: ubuntu-latest
    name: Version bump
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Bump plugin build version
        id: bump
        uses: vers-one/dotnet-project-version-updater@v1.3
        with:
          file: "SignalRgbDeckPlugin/SignalRgbDeckPlugin.csproj"
          version: bump-build

      - name: Commit Version Bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "GHA Bump project version to ${{ steps.bump.outputs.newVersion }}"
          git push --force
         
