name: Run Unit Tests On Push
 
on: [push]

permissions: write-all
jobs:
  build:
    name: MSBuild, Publish and Upload
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.3.1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
           
    - name: Restore NuGet Packages
      run: nuget restore Bill-Z-Bawb-StreamDeck-Plugins.sln
 
    - name: Build Plugin
      run: msbuild SignalRgbDeckPlugin\SignalRgbDeckPlugin.csproj /p:Configuration=Debug
    
    - name: Run xUnit Tests
      run: dotnet test SignalRgbDeckPlugin\SignalRgbDeckPlugin.csproj
